### ISSUE TITLE
Download data

### ISSUE THREAD

**Issue by dominicwhite** [DataKind-DC/census2020#3]
**to-do**

- [x] Download demographic data from Census API using tidycensus

- [x] Determine variables that will be most useful

- [x] Combine block and tract level variables

**Comment by dominicwhite** [comment]
Closed by #6 . New issues will address more specific aspects of the data pipeline.
