### ISSUE TITLE
R leaflet map

### ISSUE THREAD

**Issue by dominicwhite** [DataKind-DC/census2020#4]
**To-do**

- [x] Create R leaflet map to dynamically render the data

**Comment by dominicwhite** [comment]
Further wishlist for this issue:

- [ ] Show variables from the downloaded & merged census data.

- [ ] Switch between tract and block group display.

- [ ] Option to show user location on the map.
